### ISSUE TITLE
playground can not start up 😢

### ISSUE THREAD

**Issue by jasonChen1982** [apache/incubator-weex-playground#12]
![image](https://user-images.githubusercontent.com/8683772/62129072-63fac580-b308-11e9-8cf8-029b33687e53.png)

**Comment by wrmswindmill** [comment]
It seems that you don't execute `pod install`,please make sure you follow the ios guide：

1. Install CocoaPods.
2. Open ios directory, then execute pod install in terminal.
3. Open WeexDemo.xcworkspace with Xcode.
4. Click  (Run button)

If still has the problem, please provide more detailed information, thanks !

**Comment by jasonChen1982** [comment]
after restart my computer, it get work
